### PR TITLE
Privilege Enhancements

### PR DESCRIPTION
**Pull request by amarpriyesh**
Please review and approve the Privilege Enhancements.

### CODE REVIEW

**Review by kritikaiyeer — APPROVED** [review]
Looks good

**Review by Tejas-3098 — APPROVED** [review]
Looks good

**Review by darshi24 — APPROVED** [review]
Everything looks good, but I noticed two things that are different from the conventions we are following about variable names and collection names. First, in PrivilegeController line 26 and 27, the variable name is starting with a capital but we have been following the convention of starting variable names with small letters. Same thing in PrivilegeDao line 16. 

The second this is the collection name in PrivilegeSchema line 13. We keep collection names plural so it should be 'privileges' and not 'privilege'. It will be great if you can make these two small changes so that it keeps our code uniform. You can submit new pull request or do this in your next pull request as well. I am approving this request though. Rest all is great !!!

**Comment by amarpriyesh** [comment]
I will make the changes and send another merge request. >

**Pull request merged**
